version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123456
    ports:
      - "1433:1433"
    networks:
      - my_network

  spring-app:
    image: spring-chatapp
    depends_on:
      - sqlserver
    ports:
      - "7070:7070"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
